### ISSUE TITLE
GitHub Actions 登录时连接超时

### ISSUE THREAD

**Issue by KY-zhang-X** [KY-zhang-X/bjyouth-qndxx-action#1]
在GitHub Actions上运行脚本，会报超时错误。
错误信息如下：
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.[14](https://github.com/KY-zhang-X/bjyouth-qndxx-action/actions/runs/3391564034/jobs/5636834784#step:5:15)/x64/lib/python3.8/site-packages/urllib3/connection.py", line [17](https://github.com/KY-zhang-X/bjyouth-qndxx-action/actions/runs/3391564034/jobs/5636834784#step:5:18)4, in _new_conn
    conn = connection.create_connection(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fe674a9c760>, 'Connection to m.bjyouth.net timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.bjyouth.net', port=443): Max retries exceeded with url: /site/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe674a9c760>, 'Connection to m.bjyouth.net timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line [23](https://github.com/KY-zhang-X/bjyouth-qndxx-action/actions/runs/3391564034/jobs/5636834784#step:5:24), in main
    title = dxx.run(username, password)
  File "/home/runner/work/bjyouth-qndxx-action/bjyouth-qndxx-action/qndxx.py", line [33](https://github.com/KY-zhang-X/bjyouth-qndxx-action/actions/runs/3391564034/jobs/5636834784#step:5:34), in run
    if self.login(username, password):
  File "/home/runner/work/bjyouth-qndxx-action/bjyouth-qndxx-action/qndxx.py", line 71, in login
    captcha = self.get_captcha()
  File "/home/runner/work/bjyouth-qndxx-action/bjyouth-qndxx-action/qndxx.py", line 96, in get_captcha
    res = self.session.get(url=self.bjyouth_login_url, timeout=5)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='m.bjyouth.net', port=4[43](https://github.com/KY-zhang-X/bjyouth-qndxx-action/actions/runs/3391564034/jobs/5636834784#step:5:44)): Max retries exceeded with url: /site/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe674a9c7[60](https://github.com/KY-zhang-X/bjyouth-qndxx-action/actions/runs/3391564034/jobs/5636834784#step:5:61)>, 'Connection to m.bjyouth.net timed out. (connect timeout=5)'))
```

但是在本地运行，可以正常运行。怀疑是有针对 GitHub Actions 的反脚本措施。

**Comment by KY-zhang-X** [comment]
很可能是针对国外服务器的DNS污染，在获取`m.bjyouth.net`域名的IP地址时，海外服务器得到的IP地址是`146.19.22.103`和`91.221.116.3`这样的错误IP地址。

**Comment by KY-zhang-X** [comment]
现在允许用户添加一个国内的代理服务器，用于绕过本地DNS解析，暂时没有更好的解决方案。
可以通过添加`HTTPS_PROXY`和`HTTP_PROXY`这两个Secrets使用这个功能，如果使用的是HTTP代理服务器，内容格式为：
```
http://<username>:<password>@<host>:<port>
```
